# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'korxNew_v2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 874)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 791, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_Base = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_Base.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Base.setHorizontalSpacing(14)
        self.gridLayout_Base.setObjectName("gridLayout_Base")
        self.label_a12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_a12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a12.setObjectName("label_a12")
        self.gridLayout_Base.addWidget(self.label_a12, 10, 2, 1, 1)
        self.inp_l12 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_l12.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_l12.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_l12.setDecimals(0)
        self.inp_l12.setObjectName("inp_l12")
        self.gridLayout_Base.addWidget(self.inp_l12, 7, 2, 1, 1)
        self.inp_Lz = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_Lz.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_Lz.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_Lz.setDecimals(0)
        self.inp_Lz.setObjectName("inp_Lz")
        self.gridLayout_Base.addWidget(self.inp_Lz, 10, 8, 1, 2)
        self.label_pictureTop = QtWidgets.QLabel(self.layoutWidget)
        self.label_pictureTop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pictureTop.setWordWrap(True)
        self.label_pictureTop.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_pictureTop.setObjectName("label_pictureTop")
        self.gridLayout_Base.addWidget(self.label_pictureTop, 2, 0, 1, 2)
        self.inp_k = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_k.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_k.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_k.setDecimals(0)
        self.inp_k.setObjectName("inp_k")
        self.gridLayout_Base.addWidget(self.inp_k, 11, 3, 1, 1)
        self.label_HEAD_rollsColib = QtWidgets.QLabel(self.layoutWidget)
        self.label_HEAD_rollsColib.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HEAD_rollsColib.setWordWrap(True)
        self.label_HEAD_rollsColib.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_HEAD_rollsColib.setObjectName("label_HEAD_rollsColib")
        self.gridLayout_Base.addWidget(self.label_HEAD_rollsColib, 0, 2, 2, 2)
        self.label_m = QtWidgets.QLabel(self.layoutWidget)
        self.label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m.setObjectName("label_m")
        self.gridLayout_Base.addWidget(self.label_m, 12, 3, 1, 1)
        self.inp_a11 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_a11.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_a11.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_a11.setDecimals(0)
        self.inp_a11.setObjectName("inp_a11")
        self.gridLayout_Base.addWidget(self.inp_a11, 9, 2, 1, 1)
        self.inp_Lcmech = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_Lcmech.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_Lcmech.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_Lcmech.setDecimals(0)
        self.inp_Lcmech.setObjectName("inp_Lcmech")
        self.gridLayout_Base.addWidget(self.inp_Lcmech, 3, 5, 3, 1)
        self.frame_autofill = QtWidgets.QFrame(self.layoutWidget)
        self.frame_autofill.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_autofill.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_autofill.setObjectName("frame_autofill")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_autofill)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_autofill = QtWidgets.QLabel(self.frame_autofill)
        self.label_autofill.setAlignment(QtCore.Qt.AlignCenter)
        self.label_autofill.setObjectName("label_autofill")
        self.gridLayout_2.addWidget(self.label_autofill, 0, 0, 1, 2)
        self.K212_btn = QtWidgets.QPushButton(self.frame_autofill)
        self.K212_btn.setObjectName("K212_btn")
        self.gridLayout_2.addWidget(self.K212_btn, 1, 0, 1, 1)
        self.K360_btn = QtWidgets.QPushButton(self.frame_autofill)
        self.K360_btn.setObjectName("K360_btn")
        self.gridLayout_2.addWidget(self.K360_btn, 1, 1, 1, 1)
        self.K255_K260_btn = QtWidgets.QPushButton(self.frame_autofill)
        self.K255_K260_btn.setObjectName("K255_K260_btn")
        self.gridLayout_2.addWidget(self.K255_K260_btn, 2, 0, 1, 1)
        self.K372_btn = QtWidgets.QPushButton(self.frame_autofill)
        self.K372_btn.setObjectName("K372_btn")
        self.gridLayout_2.addWidget(self.K372_btn, 2, 1, 1, 1)
        self.K270_btn = QtWidgets.QPushButton(self.frame_autofill)
        self.K270_btn.setObjectName("K270_btn")
        self.gridLayout_2.addWidget(self.K270_btn, 3, 0, 1, 1)
        self.K435_K444_btn = QtWidgets.QPushButton(self.frame_autofill)
        self.K435_K444_btn.setObjectName("K435_K444_btn")
        self.gridLayout_2.addWidget(self.K435_K444_btn, 3, 1, 1, 1)
        self.K288_btn = QtWidgets.QPushButton(self.frame_autofill)
        self.K288_btn.setObjectName("K288_btn")
        self.gridLayout_2.addWidget(self.K288_btn, 4, 0, 1, 1)
        self.K_clear_btn = QtWidgets.QPushButton(self.frame_autofill)
        self.K_clear_btn.setObjectName("K_clear_btn")
        self.gridLayout_2.addWidget(self.K_clear_btn, 4, 1, 1, 1)
        self.gridLayout_Base.addWidget(self.frame_autofill, 11, 7, 5, 3)
        self.inp_a12 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_a12.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_a12.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_a12.setDecimals(0)
        self.inp_a12.setObjectName("inp_a12")
        self.gridLayout_Base.addWidget(self.inp_a12, 11, 2, 1, 1)
        self.cB_inp_dz = QtWidgets.QComboBox(self.layoutWidget)
        self.cB_inp_dz.setObjectName("cB_inp_dz")
        self.gridLayout_Base.addWidget(self.cB_inp_dz, 3, 8, 3, 2)
        self.frame_RPNV = QtWidgets.QFrame(self.layoutWidget)
        self.frame_RPNV.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_RPNV.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_RPNV.setObjectName("frame_RPNV")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_RPNV)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_RPNV = QtWidgets.QCheckBox(self.frame_RPNV)
        self.checkBox_RPNV.setObjectName("checkBox_RPNV")
        self.verticalLayout.addWidget(self.checkBox_RPNV)
        self.inp_RPNV_IO = QtWidgets.QDoubleSpinBox(self.frame_RPNV)
        self.inp_RPNV_IO.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_RPNV_IO.setDecimals(0)
        self.inp_RPNV_IO.setObjectName("inp_RPNV_IO")
        self.verticalLayout.addWidget(self.inp_RPNV_IO)
        self.inp_RPNV_Dvp = QtWidgets.QDoubleSpinBox(self.frame_RPNV)
        self.inp_RPNV_Dvp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_RPNV_Dvp.setDecimals(0)
        self.inp_RPNV_Dvp.setObjectName("inp_RPNV_Dvp")
        self.verticalLayout.addWidget(self.inp_RPNV_Dvp)
        self.inp_RPNV_a = QtWidgets.QDoubleSpinBox(self.frame_RPNV)
        self.inp_RPNV_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_RPNV_a.setDecimals(0)
        self.inp_RPNV_a.setObjectName("inp_RPNV_a")
        self.verticalLayout.addWidget(self.inp_RPNV_a)
        self.gridLayout_Base.addWidget(self.frame_RPNV, 11, 10, 5, 1)
        self.label_L2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_L2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_L2.setObjectName("label_L2")
        self.gridLayout_Base.addWidget(self.label_L2, 6, 5, 1, 1)
        self.label_picture = QtWidgets.QLabel(self.layoutWidget)
        self.label_picture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_picture.setWordWrap(True)
        self.label_picture.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_picture.setObjectName("label_picture")
        self.gridLayout_Base.addWidget(self.label_picture, 3, 0, 10, 2)
        self.label_dz = QtWidgets.QLabel(self.layoutWidget)
        self.label_dz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dz.setObjectName("label_dz")
        self.gridLayout_Base.addWidget(self.label_dz, 2, 8, 1, 2)
        self.inp_Lopr = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_Lopr.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_Lopr.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_Lopr.setDecimals(0)
        self.inp_Lopr.setObjectName("inp_Lopr")
        self.gridLayout_Base.addWidget(self.inp_Lopr, 7, 7, 1, 1)
        self.label_HEAD_rulerColib = QtWidgets.QLabel(self.layoutWidget)
        self.label_HEAD_rulerColib.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HEAD_rulerColib.setWordWrap(True)
        self.label_HEAD_rulerColib.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_HEAD_rulerColib.setObjectName("label_HEAD_rulerColib")
        self.gridLayout_Base.addWidget(self.label_HEAD_rulerColib, 0, 5, 2, 1)
        self.label_Dr = QtWidgets.QLabel(self.layoutWidget)
        self.label_Dr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dr.setObjectName("label_Dr")
        self.gridLayout_Base.addWidget(self.label_Dr, 2, 10, 1, 1)
        self.inp_gamma1 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_gamma1.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_gamma1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_gamma1.setDecimals(0)
        self.inp_gamma1.setObjectName("inp_gamma1")
        self.gridLayout_Base.addWidget(self.inp_gamma1, 9, 5, 1, 1)
        self.label_HEAD_billet = QtWidgets.QLabel(self.layoutWidget)
        self.label_HEAD_billet.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HEAD_billet.setWordWrap(True)
        self.label_HEAD_billet.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_HEAD_billet.setObjectName("label_HEAD_billet")
        self.gridLayout_Base.addWidget(self.label_HEAD_billet, 0, 8, 2, 2)
        self.label_hollowBilletGeomtry = QtWidgets.QLabel(self.layoutWidget)
        self.label_hollowBilletGeomtry.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hollowBilletGeomtry.setWordWrap(True)
        self.label_hollowBilletGeomtry.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_hollowBilletGeomtry.setObjectName("label_hollowBilletGeomtry")
        self.gridLayout_Base.addWidget(self.label_hollowBilletGeomtry, 0, 10, 2, 1)
        self.inp_Dvp = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_Dvp.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_Dvp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_Dvp.setDecimals(0)
        self.inp_Dvp.setObjectName("inp_Dvp")
        self.gridLayout_Base.addWidget(self.inp_Dvp, 3, 2, 3, 1)
        self.cB_inp_beta = QtWidgets.QComboBox(self.layoutWidget)
        self.cB_inp_beta.setObjectName("cB_inp_beta")
        self.gridLayout_Base.addWidget(self.cB_inp_beta, 14, 1, 1, 1)
        self.inp_gamma2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_gamma2.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_gamma2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_gamma2.setDecimals(0)
        self.inp_gamma2.setObjectName("inp_gamma2")
        self.gridLayout_Base.addWidget(self.inp_gamma2, 11, 5, 1, 1)
        self.label_Lz = QtWidgets.QLabel(self.layoutWidget)
        self.label_Lz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lz.setObjectName("label_Lz")
        self.gridLayout_Base.addWidget(self.label_Lz, 9, 8, 1, 2)
        self.label_l12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_l12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l12.setObjectName("label_l12")
        self.gridLayout_Base.addWidget(self.label_l12, 6, 2, 1, 1)
        self.label_gamma1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_gamma1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gamma1.setObjectName("label_gamma1")
        self.gridLayout_Base.addWidget(self.label_gamma1, 8, 5, 1, 1)
        self.inp_m = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_m.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_m.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_m.setDecimals(0)
        self.inp_m.setObjectName("inp_m")
        self.gridLayout_Base.addWidget(self.inp_m, 13, 3, 1, 1)
        self.inp_lvix = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_lvix.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_lvix.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_lvix.setDecimals(0)
        self.inp_lvix.setObjectName("inp_lvix")
        self.gridLayout_Base.addWidget(self.inp_lvix, 9, 3, 1, 1)
        self.label_Lopr = QtWidgets.QLabel(self.layoutWidget)
        self.label_Lopr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lopr.setObjectName("label_Lopr")
        self.gridLayout_Base.addWidget(self.label_Lopr, 6, 7, 1, 1)
        self.label_Lvx = QtWidgets.QLabel(self.layoutWidget)
        self.label_Lvx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lvx.setObjectName("label_Lvx")
        self.gridLayout_Base.addWidget(self.label_Lvx, 6, 3, 1, 1)
        self.label_a2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a2.setObjectName("label_a2")
        self.gridLayout_Base.addWidget(self.label_a2, 12, 2, 1, 1)
        self.inp_fi = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_fi.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_fi.setDecimals(0)
        self.inp_fi.setObjectName("inp_fi")
        self.gridLayout_Base.addWidget(self.inp_fi, 14, 0, 1, 1)
        self.label_HEAD_insertColib = QtWidgets.QLabel(self.layoutWidget)
        self.label_HEAD_insertColib.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HEAD_insertColib.setWordWrap(True)
        self.label_HEAD_insertColib.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_HEAD_insertColib.setObjectName("label_HEAD_insertColib")
        self.gridLayout_Base.addWidget(self.label_HEAD_insertColib, 0, 7, 2, 1)
        self.label_Lrab = QtWidgets.QLabel(self.layoutWidget)
        self.label_Lrab.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lrab.setObjectName("label_Lrab")
        self.gridLayout_Base.addWidget(self.label_Lrab, 2, 3, 1, 1)
        self.inp_a2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_a2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_a2.setDecimals(0)
        self.inp_a2.setObjectName("inp_a2")
        self.gridLayout_Base.addWidget(self.inp_a2, 13, 2, 1, 1)
        self.label_fi = QtWidgets.QLabel(self.layoutWidget)
        self.label_fi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fi.setObjectName("label_fi")
        self.gridLayout_Base.addWidget(self.label_fi, 13, 0, 1, 1)
        self.label_beta = QtWidgets.QLabel(self.layoutWidget)
        self.label_beta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_beta.setObjectName("label_beta")
        self.gridLayout_Base.addWidget(self.label_beta, 13, 1, 1, 1)
        self.inp_Lrab = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_Lrab.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_Lrab.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_Lrab.setDecimals(0)
        self.inp_Lrab.setObjectName("inp_Lrab")
        self.gridLayout_Base.addWidget(self.inp_Lrab, 3, 3, 3, 1)
        self.label_k = QtWidgets.QLabel(self.layoutWidget)
        self.label_k.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k.setObjectName("label_k")
        self.gridLayout_Base.addWidget(self.label_k, 10, 3, 1, 1)
        self.label_HEAD_scheme = QtWidgets.QLabel(self.layoutWidget)
        self.label_HEAD_scheme.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HEAD_scheme.setWordWrap(True)
        self.label_HEAD_scheme.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_HEAD_scheme.setObjectName("label_HEAD_scheme")
        self.gridLayout_Base.addWidget(self.label_HEAD_scheme, 0, 0, 2, 2)
        self.inp_Dr = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_Dr.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_Dr.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_Dr.setDecimals(0)
        self.inp_Dr.setObjectName("inp_Dr")
        self.gridLayout_Base.addWidget(self.inp_Dr, 3, 10, 3, 1)
        self.label_Lvix = QtWidgets.QLabel(self.layoutWidget)
        self.label_Lvix.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lvix.setObjectName("label_Lvix")
        self.gridLayout_Base.addWidget(self.label_Lvix, 8, 3, 1, 1)
        self.label_dopr = QtWidgets.QLabel(self.layoutWidget)
        self.label_dopr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dopr.setObjectName("label_dopr")
        self.gridLayout_Base.addWidget(self.label_dopr, 2, 7, 1, 1)
        self.label_Lcmech = QtWidgets.QLabel(self.layoutWidget)
        self.label_Lcmech.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lcmech.setObjectName("label_Lcmech")
        self.gridLayout_Base.addWidget(self.label_Lcmech, 2, 5, 1, 1)
        self.inp_L2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_L2.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_L2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_L2.setDecimals(0)
        self.inp_L2.setObjectName("inp_L2")
        self.gridLayout_Base.addWidget(self.inp_L2, 7, 5, 1, 1)
        self.inp_dopr = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_dopr.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_dopr.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_dopr.setDecimals(0)
        self.inp_dopr.setObjectName("inp_dopr")
        self.gridLayout_Base.addWidget(self.inp_dopr, 3, 7, 3, 1)
        self.label_Dvp = QtWidgets.QLabel(self.layoutWidget)
        self.label_Dvp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp.setObjectName("label_Dvp")
        self.gridLayout_Base.addWidget(self.label_Dvp, 2, 2, 1, 1)
        self.label_gamma2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_gamma2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gamma2.setObjectName("label_gamma2")
        self.gridLayout_Base.addWidget(self.label_gamma2, 10, 5, 1, 1)
        self.inp_Lvx = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inp_Lvx.setAlignment(QtCore.Qt.AlignCenter)
        self.inp_Lvx.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_Lvx.setDecimals(0)
        self.inp_Lvx.setObjectName("inp_Lvx")
        self.gridLayout_Base.addWidget(self.inp_Lvx, 7, 3, 1, 1)
        self.label_a11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_a11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a11.setObjectName("label_a11")
        self.gridLayout_Base.addWidget(self.label_a11, 8, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radio_factor1 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_factor1.setObjectName("radio_factor1")
        self.verticalLayout_2.addWidget(self.radio_factor1)
        self.radio_factor2 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_factor2.setObjectName("radio_factor2")
        self.verticalLayout_2.addWidget(self.radio_factor2)
        self.radio_factor3 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_factor3.setObjectName("radio_factor3")
        self.verticalLayout_2.addWidget(self.radio_factor3)
        self.gridLayout_Base.addWidget(self.groupBox, 6, 8, 3, 2)
        self.frame_Exit = QtWidgets.QFrame(self.layoutWidget)
        self.frame_Exit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Exit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Exit.setObjectName("frame_Exit")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_Exit)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radio_openExit = QtWidgets.QRadioButton(self.frame_Exit)
        self.radio_openExit.setObjectName("radio_openExit")
        self.gridLayout_6.addWidget(self.radio_openExit, 0, 0, 1, 1)
        self.radio_closeExit = QtWidgets.QRadioButton(self.frame_Exit)
        self.radio_closeExit.setObjectName("radio_closeExit")
        self.gridLayout_6.addWidget(self.radio_closeExit, 1, 0, 1, 1)
        self.gridLayout_Base.addWidget(self.frame_Exit, 14, 2, 2, 4)
        self.frame_Srdr = QtWidgets.QFrame(self.layoutWidget)
        self.frame_Srdr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Srdr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Srdr.setObjectName("frame_Srdr")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_Srdr)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radio_Sr = QtWidgets.QRadioButton(self.frame_Srdr)
        self.radio_Sr.setObjectName("radio_Sr")
        self.gridLayout_7.addWidget(self.radio_Sr, 0, 0, 1, 1)
        self.inp_radio_Sr = QtWidgets.QDoubleSpinBox(self.frame_Srdr)
        self.inp_radio_Sr.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_radio_Sr.setDecimals(0)
        self.inp_radio_Sr.setObjectName("inp_radio_Sr")
        self.gridLayout_7.addWidget(self.inp_radio_Sr, 1, 0, 1, 1)
        self.radio_dr = QtWidgets.QRadioButton(self.frame_Srdr)
        self.radio_dr.setObjectName("radio_dr")
        self.gridLayout_7.addWidget(self.radio_dr, 2, 0, 1, 1)
        self.inp_radio_dr = QtWidgets.QDoubleSpinBox(self.frame_Srdr)
        self.inp_radio_dr.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inp_radio_dr.setDecimals(0)
        self.inp_radio_dr.setObjectName("inp_radio_dr")
        self.gridLayout_7.addWidget(self.inp_radio_dr, 3, 0, 1, 1)
        self.gridLayout_Base.addWidget(self.frame_Srdr, 6, 10, 5, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(810, 10, 251, 441))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_GPON_all = QtWidgets.QGridLayout()
        self.gridLayout_GPON_all.setObjectName("gridLayout_GPON_all")
        self.label_GPOD_En = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_En.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_En.setObjectName("label_GPOD_En")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_En, 5, 0, 1, 1)
        self.label_GPOD_Lr = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_Lr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_Lr.setObjectName("label_GPOD_Lr")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_Lr, 7, 0, 1, 1)
        self.inOut_GPOD_Een = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_Een.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_Een.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_Een.setDecimals(0)
        self.inOut_GPOD_Een.setObjectName("inOut_GPOD_Een")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_Een, 6, 2, 1, 1)
        self.checkBox_label_GPOD_ksi = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_label_GPOD_ksi.setObjectName("checkBox_label_GPOD_ksi")
        self.gridLayout_GPON_all.addWidget(self.checkBox_label_GPOD_ksi, 5, 1, 1, 1)
        self.label_GPOD_a = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_a.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_a.setObjectName("label_GPOD_a")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_a, 3, 0, 1, 1)
        self.inOut_GPOD_mu = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_mu.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_mu.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_mu.setDecimals(0)
        self.inOut_GPOD_mu.setObjectName("inOut_GPOD_mu")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_mu, 8, 1, 1, 1)
        self.radio_GPOD_roolsDistance = QtWidgets.QRadioButton(self.frame_3)
        self.radio_GPOD_roolsDistance.setObjectName("radio_GPOD_roolsDistance")
        self.gridLayout_GPON_all.addWidget(self.radio_GPOD_roolsDistance, 1, 0, 1, 3)
        self.inOut_GPOD_GF = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_GF.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_GF.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_GF.setDecimals(0)
        self.inOut_GPOD_GF.setObjectName("inOut_GPOD_GF")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_GF, 8, 2, 1, 1)
        self.label_GPOD_b = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_b.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_b.setObjectName("label_GPOD_b")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_b, 3, 1, 1, 1)
        self.inOut_GPOD_Dvix = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_Dvix.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_Dvix.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_Dvix.setDecimals(0)
        self.inOut_GPOD_Dvix.setObjectName("inOut_GPOD_Dvix")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_Dvix, 10, 1, 1, 1)
        self.inOut_GPOD_Dvx = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_Dvx.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_Dvx.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_Dvx.setDecimals(0)
        self.inOut_GPOD_Dvx.setObjectName("inOut_GPOD_Dvx")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_Dvx, 10, 0, 1, 1)
        self.inOut_GPOD_X2 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_X2.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_X2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_X2.setDecimals(0)
        self.inOut_GPOD_X2.setObjectName("inOut_GPOD_X2")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_X2, 12, 1, 1, 1)
        self.label_GPOD_c = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_c.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_c.setObjectName("label_GPOD_c")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_c, 3, 2, 1, 1)
        self.label_GPOD_Een = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_Een.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_Een.setObjectName("label_GPOD_Een")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_Een, 5, 2, 1, 1)
        self.inOut_GPOD_ksi = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_ksi.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_ksi.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_ksi.setDecimals(0)
        self.inOut_GPOD_ksi.setObjectName("inOut_GPOD_ksi")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_ksi, 6, 1, 1, 1)
        self.inOut_GPOD_En = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_En.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_En.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_En.setDecimals(0)
        self.inOut_GPOD_En.setObjectName("inOut_GPOD_En")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_En, 6, 0, 1, 1)
        self.inOut_GPOD_L = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_L.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_L.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_L.setDecimals(0)
        self.inOut_GPOD_L.setObjectName("inOut_GPOD_L")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_L, 10, 2, 1, 1)
        self.label_GPOD_Lod = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_Lod.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_Lod.setObjectName("label_GPOD_Lod")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_Lod, 11, 2, 1, 1)
        self.inOut_GPOD_X1 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_X1.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_X1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_X1.setDecimals(0)
        self.inOut_GPOD_X1.setObjectName("inOut_GPOD_X1")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_X1, 12, 0, 1, 1)
        self.inOut_GPOD_Lod = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_Lod.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_Lod.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_Lod.setDecimals(0)
        self.inOut_GPOD_Lod.setObjectName("inOut_GPOD_Lod")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_Lod, 12, 2, 1, 1)
        self.label_GPOD_Dvix = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_Dvix.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_Dvix.setObjectName("label_GPOD_Dvix")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_Dvix, 9, 1, 1, 1)
        self.radio_GPOD_pitchReduction = QtWidgets.QRadioButton(self.frame_3)
        self.radio_GPOD_pitchReduction.setObjectName("radio_GPOD_pitchReduction")
        self.gridLayout_GPON_all.addWidget(self.radio_GPOD_pitchReduction, 2, 0, 1, 3)
        self.label_HEAD_GPOD = QtWidgets.QLabel(self.frame_3)
        self.label_HEAD_GPOD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HEAD_GPOD.setWordWrap(True)
        self.label_HEAD_GPOD.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_HEAD_GPOD.setObjectName("label_HEAD_GPOD")
        self.gridLayout_GPON_all.addWidget(self.label_HEAD_GPOD, 0, 0, 1, 3)
        self.label_GPOD_mu = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_mu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_mu.setObjectName("label_GPOD_mu")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_mu, 7, 1, 1, 1)
        self.inOut_GPOD_a = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_a.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_a.setDecimals(0)
        self.inOut_GPOD_a.setObjectName("inOut_GPOD_a")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_a, 4, 0, 1, 1)
        self.inOut_GPOD_c = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_c.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_c.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_c.setDecimals(0)
        self.inOut_GPOD_c.setObjectName("inOut_GPOD_c")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_c, 4, 2, 1, 1)
        self.label_GPOD_GF = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_GF.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_GF.setObjectName("label_GPOD_GF")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_GF, 7, 2, 1, 1)
        self.inOut_GPOD_b = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_b.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_b.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_b.setDecimals(0)
        self.inOut_GPOD_b.setObjectName("inOut_GPOD_b")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_b, 4, 1, 1, 1)
        self.label_GPOD_Dvx = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_Dvx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_Dvx.setObjectName("label_GPOD_Dvx")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_Dvx, 9, 0, 1, 1)
        self.inOut_GPOD_Lr = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.inOut_GPOD_Lr.setAlignment(QtCore.Qt.AlignCenter)
        self.inOut_GPOD_Lr.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inOut_GPOD_Lr.setDecimals(0)
        self.inOut_GPOD_Lr.setObjectName("inOut_GPOD_Lr")
        self.gridLayout_GPON_all.addWidget(self.inOut_GPOD_Lr, 8, 0, 1, 1)
        self.label_GPOD_X2 = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_X2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_X2.setObjectName("label_GPOD_X2")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_X2, 11, 1, 1, 1)
        self.label_GPOD_L = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_L.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_L.setObjectName("label_GPOD_L")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_L, 9, 2, 1, 1)
        self.label_GPOD_X1 = QtWidgets.QLabel(self.frame_3)
        self.label_GPOD_X1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GPOD_X1.setObjectName("label_GPOD_X1")
        self.gridLayout_GPON_all.addWidget(self.label_GPOD_X1, 11, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_GPON_all, 0, 0, 1, 1)
        self.gridLayout_GPOD_butons = QtWidgets.QGridLayout()
        self.gridLayout_GPOD_butons.setObjectName("gridLayout_GPOD_butons")
        self.Coun_btn = QtWidgets.QPushButton(self.frame_3)
        self.Coun_btn.setMinimumSize(QtCore.QSize(0, 34))
        self.Coun_btn.setObjectName("Coun_btn")
        self.gridLayout_GPOD_butons.addWidget(self.Coun_btn, 0, 0, 1, 1)
        self.FormTable_btn = QtWidgets.QPushButton(self.frame_3)
        self.FormTable_btn.setObjectName("FormTable_btn")
        self.gridLayout_GPOD_butons.addWidget(self.FormTable_btn, 0, 1, 1, 1)
        self.FastCount_btn = QtWidgets.QPushButton(self.frame_3)
        self.FastCount_btn.setMinimumSize(QtCore.QSize(0, 34))
        self.FastCount_btn.setObjectName("FastCount_btn")
        self.gridLayout_GPOD_butons.addWidget(self.FastCount_btn, 1, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_GPOD_butons, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_a12.setText(_translate("MainWindow", "a12"))
        self.label_pictureTop.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">К288</span></p></body></html>"))
        self.label_HEAD_rollsColib.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Калибровка валков</span></p></body></html>"))
        self.label_m.setText(_translate("MainWindow", "m"))
        self.label_autofill.setText(_translate("MainWindow", "Автозаполнение"))
        self.K212_btn.setText(_translate("MainWindow", "K212"))
        self.K360_btn.setText(_translate("MainWindow", "K360"))
        self.K255_K260_btn.setText(_translate("MainWindow", "K255/K260"))
        self.K372_btn.setText(_translate("MainWindow", "K372"))
        self.K270_btn.setText(_translate("MainWindow", "K270"))
        self.K435_K444_btn.setText(_translate("MainWindow", "K435/K444"))
        self.K288_btn.setText(_translate("MainWindow", "K288"))
        self.K_clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.checkBox_RPNV.setText(_translate("MainWindow", "Расч. полож. \n"
"нажимных винтов от \n"
"базовой настройки"))
        self.inp_RPNV_IO.setSpecialValueText(_translate("MainWindow", "IO"))
        self.inp_RPNV_Dvp.setSpecialValueText(_translate("MainWindow", "Dвп"))
        self.inp_RPNV_a.setSpecialValueText(_translate("MainWindow", "a"))
        self.label_L2.setText(_translate("MainWindow", "L2"))
        self.label_picture.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/left-image.png\"/></p></body></html>"))
        self.label_dz.setText(_translate("MainWindow", "dз"))
        self.label_HEAD_rulerColib.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Калибровка линеек</span></p></body></html>"))
        self.label_Dr.setText(_translate("MainWindow", "Dr"))
        self.label_HEAD_billet.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Заготовка</span></p></body></html>"))
        self.label_hollowBilletGeomtry.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Геометрия гильзы</span></p></body></html>"))
        self.label_Lz.setText(_translate("MainWindow", "Lз"))
        self.label_l12.setText(_translate("MainWindow", "l12"))
        self.label_gamma1.setText(_translate("MainWindow", "gamma1"))
        self.label_Lopr.setText(_translate("MainWindow", "Lопр"))
        self.label_Lvx.setText(_translate("MainWindow", "Lвх"))
        self.label_a2.setText(_translate("MainWindow", "a2"))
        self.label_HEAD_insertColib.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Калибровка оправки</span></p></body></html>"))
        self.label_Lrab.setText(_translate("MainWindow", "Lраб"))
        self.label_fi.setText(_translate("MainWindow", "fi"))
        self.label_beta.setText(_translate("MainWindow", "beta"))
        self.label_k.setText(_translate("MainWindow", "k"))
        self.label_HEAD_scheme.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Расчетная схема очага деформации прошивного стана</span></p></body></html>"))
        self.label_Lvix.setText(_translate("MainWindow", "Lвых"))
        self.label_dopr.setText(_translate("MainWindow", "dопр"))
        self.label_Lcmech.setText(_translate("MainWindow", "Lсмещ"))
        self.label_Dvp.setText(_translate("MainWindow", "Dвп"))
        self.label_gamma2.setText(_translate("MainWindow", "gamma2"))
        self.label_a11.setText(_translate("MainWindow", "a11"))
        self.groupBox.setTitle(_translate("MainWindow", "Кратность"))
        self.radio_factor1.setText(_translate("MainWindow", "/1"))
        self.radio_factor2.setText(_translate("MainWindow", "/2"))
        self.radio_factor3.setText(_translate("MainWindow", "/3"))
        self.radio_openExit.setText(_translate("MainWindow", "Угол раскатки в строну раскрытия выхода"))
        self.radio_closeExit.setText(_translate("MainWindow", "Угол раскатки в строну закрытия выхода"))
        self.radio_Sr.setText(_translate("MainWindow", "Sr"))
        self.radio_dr.setText(_translate("MainWindow", "dr"))
        self.label_GPOD_En.setText(_translate("MainWindow", "En"))
        self.label_GPOD_Lr.setText(_translate("MainWindow", "Lr"))
        self.checkBox_label_GPOD_ksi.setText(_translate("MainWindow", "ksi"))
        self.label_GPOD_a.setText(_translate("MainWindow", "a"))
        self.radio_GPOD_roolsDistance.setText(_translate("MainWindow", "Задать расстояние между валками, мм"))
        self.label_GPOD_b.setText(_translate("MainWindow", "b"))
        self.label_GPOD_c.setText(_translate("MainWindow", "c"))
        self.label_GPOD_Een.setText(_translate("MainWindow", "Eн"))
        self.label_GPOD_Lod.setText(_translate("MainWindow", "Lод"))
        self.label_GPOD_Dvix.setText(_translate("MainWindow", "Dвых"))
        self.radio_GPOD_pitchReduction.setText(_translate("MainWindow", "Задать обжатие в пережиме, %"))
        self.label_HEAD_GPOD.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Геометрические параметры очага деформации</span></p></body></html>"))
        self.label_GPOD_mu.setText(_translate("MainWindow", "mu"))
        self.label_GPOD_GF.setText(_translate("MainWindow", "GF"))
        self.label_GPOD_Dvx.setText(_translate("MainWindow", "Dвх"))
        self.label_GPOD_X2.setText(_translate("MainWindow", "X2"))
        self.label_GPOD_L.setText(_translate("MainWindow", "L"))
        self.label_GPOD_X1.setText(_translate("MainWindow", "X1"))
        self.Coun_btn.setText(_translate("MainWindow", "Рассчитать"))
        self.FormTable_btn.setText(_translate("MainWindow", "Сформировать \n"
"в виде таблицы"))
        self.FastCount_btn.setText(_translate("MainWindow", "Быстрый расчет"))
import source_rc
