# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_table.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1242, 786)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1222, 766))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tbl_main_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.tbl_main_widget.setObjectName("tbl_main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tbl_main_widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tbl_b = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_b.setFont(font)
        self.tbl_b.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_b.setWordWrap(True)
        self.tbl_b.setObjectName("tbl_b")
        self.gridLayout.addWidget(self.tbl_b, 3, 5, 1, 1)
        self.tbl_En = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_En.setFont(font)
        self.tbl_En.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_En.setWordWrap(True)
        self.tbl_En.setObjectName("tbl_En")
        self.gridLayout.addWidget(self.tbl_En, 5, 6, 1, 1)
        self.label_Dvp_42 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_42.setWordWrap(True)
        self.label_Dvp_42.setObjectName("label_Dvp_42")
        self.gridLayout.addWidget(self.label_Dvp_42, 7, 5, 1, 1)
        self.tbl_Lz = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Lz.setFont(font)
        self.tbl_Lz.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Lz.setWordWrap(True)
        self.tbl_Lz.setObjectName("tbl_Lz")
        self.gridLayout.addWidget(self.tbl_Lz, 5, 1, 1, 1)
        self.tbl_Lopr = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Lopr.setFont(font)
        self.tbl_Lopr.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Lopr.setWordWrap(True)
        self.tbl_Lopr.setObjectName("tbl_Lopr")
        self.gridLayout.addWidget(self.tbl_Lopr, 5, 3, 1, 1)
        self.tbl_date = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbl_date.setFont(font)
        self.tbl_date.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_date.setWordWrap(True)
        self.tbl_date.setObjectName("tbl_date")
        self.gridLayout.addWidget(self.tbl_date, 0, 0, 1, 1)
        self.label_Dvp_5 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_5.setWordWrap(True)
        self.label_Dvp_5.setObjectName("label_Dvp_5")
        self.gridLayout.addWidget(self.label_Dvp_5, 2, 6, 1, 1)
        self.label_Dvp_38 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_38.setWordWrap(True)
        self.label_Dvp_38.setObjectName("label_Dvp_38")
        self.gridLayout.addWidget(self.label_Dvp_38, 7, 2, 1, 1)
        self.label_Dvp_34 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_34.setWordWrap(True)
        self.label_Dvp_34.setObjectName("label_Dvp_34")
        self.gridLayout.addWidget(self.label_Dvp_34, 7, 6, 1, 1)
        self.tbl_btn_print = QtWidgets.QPushButton(self.tbl_main_widget)
        self.tbl_btn_print.setDefault(True)
        self.tbl_btn_print.setObjectName("tbl_btn_print")
        self.gridLayout.addWidget(self.tbl_btn_print, 4, 8, 1, 1)
        self.tbl_Dopr = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Dopr.setFont(font)
        self.tbl_Dopr.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Dopr.setWordWrap(True)
        self.tbl_Dopr.setObjectName("tbl_Dopr")
        self.gridLayout.addWidget(self.tbl_Dopr, 3, 3, 1, 1)
        self.tbl_Dvh = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Dvh.setFont(font)
        self.tbl_Dvh.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Dvh.setWordWrap(True)
        self.tbl_Dvh.setObjectName("tbl_Dvh")
        self.gridLayout.addWidget(self.tbl_Dvh, 8, 3, 1, 1)
        self.tbl_Sg = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Sg.setFont(font)
        self.tbl_Sg.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Sg.setWordWrap(True)
        self.tbl_Sg.setObjectName("tbl_Sg")
        self.gridLayout.addWidget(self.tbl_Sg, 8, 1, 1, 1)
        self.tbl_GF = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_GF.setFont(font)
        self.tbl_GF.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_GF.setWordWrap(True)
        self.tbl_GF.setObjectName("tbl_GF")
        self.gridLayout.addWidget(self.tbl_GF, 8, 8, 1, 1)
        self.label_Dvp_6 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_6.setWordWrap(True)
        self.label_Dvp_6.setObjectName("label_Dvp_6")
        self.gridLayout.addWidget(self.label_Dvp_6, 4, 6, 1, 1)
        self.label_Dvp_36 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_36.setWordWrap(True)
        self.label_Dvp_36.setObjectName("label_Dvp_36")
        self.gridLayout.addWidget(self.label_Dvp_36, 7, 4, 1, 1)
        self.tbl_ksi = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_ksi.setFont(font)
        self.tbl_ksi.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_ksi.setWordWrap(True)
        self.tbl_ksi.setObjectName("tbl_ksi")
        self.gridLayout.addWidget(self.tbl_ksi, 8, 5, 1, 1)
        self.label_Dvp_2 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_2.setWordWrap(True)
        self.label_Dvp_2.setObjectName("label_Dvp_2")
        self.gridLayout.addWidget(self.label_Dvp_2, 2, 1, 1, 1)
        self.label_Dvp_12 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_12.setWordWrap(True)
        self.label_Dvp_12.setObjectName("label_Dvp_12")
        self.gridLayout.addWidget(self.label_Dvp_12, 4, 0, 1, 1)
        self.label_Dvp_10 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_10.setWordWrap(True)
        self.label_Dvp_10.setObjectName("label_Dvp_10")
        self.gridLayout.addWidget(self.label_Dvp_10, 4, 3, 1, 1)
        self.tbl_button = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbl_button.setFont(font)
        self.tbl_button.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_button.setWordWrap(True)
        self.tbl_button.setObjectName("tbl_button")
        self.gridLayout.addWidget(self.tbl_button, 0, 1, 1, 1)
        self.label_Dvp_13 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_13.setWordWrap(True)
        self.label_Dvp_13.setObjectName("label_Dvp_13")
        self.gridLayout.addWidget(self.label_Dvp_13, 4, 1, 1, 1)
        self.tbl_Lg = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Lg.setFont(font)
        self.tbl_Lg.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Lg.setWordWrap(True)
        self.tbl_Lg.setObjectName("tbl_Lg")
        self.gridLayout.addWidget(self.tbl_Lg, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.tbl_main_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 9)
        self.label_Dvp_31 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_31.setWordWrap(True)
        self.label_Dvp_31.setObjectName("label_Dvp_31")
        self.gridLayout.addWidget(self.label_Dvp_31, 7, 0, 1, 1)
        self.tbl_Dvp = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Dvp.setFont(font)
        self.tbl_Dvp.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Dvp.setWordWrap(True)
        self.tbl_Dvp.setObjectName("tbl_Dvp")
        self.gridLayout.addWidget(self.tbl_Dvp, 3, 0, 1, 1)
        self.tbl_btn_save = QtWidgets.QPushButton(self.tbl_main_widget)
        self.tbl_btn_save.setObjectName("tbl_btn_save")
        self.gridLayout.addWidget(self.tbl_btn_save, 3, 8, 1, 1)
        self.label_Dvp_9 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_9.setWordWrap(True)
        self.label_Dvp_9.setObjectName("label_Dvp_9")
        self.gridLayout.addWidget(self.label_Dvp_9, 4, 5, 1, 1)
        self.label_Dvp_7 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_7.setWordWrap(True)
        self.label_Dvp_7.setObjectName("label_Dvp_7")
        self.gridLayout.addWidget(self.label_Dvp_7, 2, 4, 1, 1)
        self.tbl_a = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_a.setFont(font)
        self.tbl_a.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_a.setWordWrap(True)
        self.tbl_a.setObjectName("tbl_a")
        self.gridLayout.addWidget(self.tbl_a, 3, 4, 1, 1)
        self.tbl_L = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_L.setFont(font)
        self.tbl_L.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_L.setWordWrap(True)
        self.tbl_L.setObjectName("tbl_L")
        self.gridLayout.addWidget(self.tbl_L, 5, 5, 1, 1)
        self.label_Dvp_3 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_3.setWordWrap(True)
        self.label_Dvp_3.setObjectName("label_Dvp_3")
        self.gridLayout.addWidget(self.label_Dvp_3, 2, 3, 1, 1)
        self.label_Dvp_37 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_37.setWordWrap(True)
        self.label_Dvp_37.setObjectName("label_Dvp_37")
        self.gridLayout.addWidget(self.label_Dvp_37, 7, 1, 1, 1)
        self.label_Dvp_43 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_43.setWordWrap(True)
        self.label_Dvp_43.setObjectName("label_Dvp_43")
        self.gridLayout.addWidget(self.label_Dvp_43, 7, 7, 1, 1)
        self.tbl_Dvih = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Dvih.setFont(font)
        self.tbl_Dvih.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Dvih.setWordWrap(True)
        self.tbl_Dvih.setObjectName("tbl_Dvih")
        self.gridLayout.addWidget(self.tbl_Dvih, 8, 4, 1, 1)
        self.tbl_Een = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Een.setFont(font)
        self.tbl_Een.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Een.setWordWrap(True)
        self.tbl_Een.setObjectName("tbl_Een")
        self.gridLayout.addWidget(self.tbl_Een, 3, 6, 1, 1)
        self.label_Dvp = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp.setWordWrap(True)
        self.label_Dvp.setObjectName("label_Dvp")
        self.gridLayout.addWidget(self.label_Dvp, 2, 0, 1, 1)
        self.tbl_dg = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_dg.setFont(font)
        self.tbl_dg.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_dg.setWordWrap(True)
        self.tbl_dg.setObjectName("tbl_dg")
        self.gridLayout.addWidget(self.tbl_dg, 8, 0, 1, 1)
        self.label_Dvp_45 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_45.setWordWrap(True)
        self.label_Dvp_45.setObjectName("label_Dvp_45")
        self.gridLayout.addWidget(self.label_Dvp_45, 7, 8, 1, 1)
        self.label_Dvp_41 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_41.setWordWrap(True)
        self.label_Dvp_41.setObjectName("label_Dvp_41")
        self.gridLayout.addWidget(self.label_Dvp_41, 7, 3, 1, 1)
        self.tbl_beta = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_beta.setFont(font)
        self.tbl_beta.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_beta.setWordWrap(True)
        self.tbl_beta.setObjectName("tbl_beta")
        self.gridLayout.addWidget(self.tbl_beta, 8, 6, 1, 1)
        self.label_Dvp_8 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_8.setWordWrap(True)
        self.label_Dvp_8.setObjectName("label_Dvp_8")
        self.gridLayout.addWidget(self.label_Dvp_8, 2, 5, 1, 1)
        self.label_Dvp_4 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_4.setWordWrap(True)
        self.label_Dvp_4.setObjectName("label_Dvp_4")
        self.gridLayout.addWidget(self.label_Dvp_4, 2, 2, 1, 1)
        self.label_Dvp_11 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_11.setWordWrap(True)
        self.label_Dvp_11.setObjectName("label_Dvp_11")
        self.gridLayout.addWidget(self.label_Dvp_11, 4, 4, 1, 1)
        self.tbl_mu = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_mu.setFont(font)
        self.tbl_mu.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_mu.setWordWrap(True)
        self.tbl_mu.setObjectName("tbl_mu")
        self.gridLayout.addWidget(self.tbl_mu, 8, 2, 1, 1)
        self.tbl_Dz = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Dz.setFont(font)
        self.tbl_Dz.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Dz.setWordWrap(True)
        self.tbl_Dz.setObjectName("tbl_Dz")
        self.gridLayout.addWidget(self.tbl_Dz, 3, 1, 1, 1)
        self.tbl_screws = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_screws.setFont(font)
        self.tbl_screws.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_screws.setWordWrap(True)
        self.tbl_screws.setObjectName("tbl_screws")
        self.gridLayout.addWidget(self.tbl_screws, 5, 0, 1, 1)
        self.tbl_fi = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_fi.setFont(font)
        self.tbl_fi.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_fi.setWordWrap(True)
        self.tbl_fi.setObjectName("tbl_fi")
        self.gridLayout.addWidget(self.tbl_fi, 8, 7, 1, 1)
        self.label_Dvp_14 = QtWidgets.QLabel(self.tbl_main_widget)
        self.label_Dvp_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Dvp_14.setWordWrap(True)
        self.label_Dvp_14.setObjectName("label_Dvp_14")
        self.gridLayout.addWidget(self.label_Dvp_14, 4, 2, 1, 1)
        self.tbl_c = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_c.setFont(font)
        self.tbl_c.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_c.setWordWrap(True)
        self.tbl_c.setObjectName("tbl_c")
        self.gridLayout.addWidget(self.tbl_c, 5, 4, 1, 1)
        self.tbl_Dg = QtWidgets.QLabel(self.tbl_main_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_Dg.setFont(font)
        self.tbl_Dg.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_Dg.setWordWrap(True)
        self.tbl_Dg.setObjectName("tbl_Dg")
        self.gridLayout.addWidget(self.tbl_Dg, 3, 2, 1, 1)
        self.tbl_line = QtWidgets.QLineEdit(self.tbl_main_widget)
        self.tbl_line.setMinimumSize(QtCore.QSize(950, 0))
        self.tbl_line.setObjectName("tbl_line")
        self.gridLayout.addWidget(self.tbl_line, 1, 0, 1, 7)
        self.frame = QtWidgets.QFrame(self.tbl_main_widget)
        self.frame.setMinimumSize(QtCore.QSize(0, 480))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 1191, 471))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tbl_chart_X1 = QtWidgets.QLabel(self.frame)
        self.tbl_chart_X1.setGeometry(QtCore.QRect(340, 80, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_X1.setFont(font)
        self.tbl_chart_X1.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_X1.setObjectName("tbl_chart_X1")
        self.tbl_chart_Dz = QtWidgets.QLabel(self.frame)
        self.tbl_chart_Dz.setGeometry(QtCore.QRect(150, 220, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_Dz.setFont(font)
        self.tbl_chart_Dz.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_Dz.setObjectName("tbl_chart_Dz")
        self.tbl_chart_c = QtWidgets.QLabel(self.frame)
        self.tbl_chart_c.setGeometry(QtCore.QRect(490, 200, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_c.setFont(font)
        self.tbl_chart_c.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_c.setObjectName("tbl_chart_c")
        self.tbl_chart_Dopr = QtWidgets.QLabel(self.frame)
        self.tbl_chart_Dopr.setGeometry(QtCore.QRect(780, 200, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_Dopr.setFont(font)
        self.tbl_chart_Dopr.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_Dopr.setObjectName("tbl_chart_Dopr")
        self.tbl_chart_Dg = QtWidgets.QLabel(self.frame)
        self.tbl_chart_Dg.setGeometry(QtCore.QRect(990, 210, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_Dg.setFont(font)
        self.tbl_chart_Dg.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_Dg.setObjectName("tbl_chart_Dg")
        self.tbl_chart_Lopr = QtWidgets.QLabel(self.frame)
        self.tbl_chart_Lopr.setGeometry(QtCore.QRect(570, 420, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_Lopr.setFont(font)
        self.tbl_chart_Lopr.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_Lopr.setObjectName("tbl_chart_Lopr")
        self.tbl_chart_b = QtWidgets.QLabel(self.frame)
        self.tbl_chart_b.setGeometry(QtCore.QRect(590, 250, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_b.setFont(font)
        self.tbl_chart_b.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_b.setObjectName("tbl_chart_b")
        self.tbl_chart_a = QtWidgets.QLabel(self.frame)
        self.tbl_chart_a.setGeometry(QtCore.QRect(590, 170, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_a.setFont(font)
        self.tbl_chart_a.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_a.setObjectName("tbl_chart_a")
        self.tbl_chart_Sg = QtWidgets.QLabel(self.frame)
        self.tbl_chart_Sg.setGeometry(QtCore.QRect(870, 180, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_Sg.setFont(font)
        self.tbl_chart_Sg.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_Sg.setObjectName("tbl_chart_Sg")
        self.tbl_chart_err_msg = QtWidgets.QLabel(self.frame)
        self.tbl_chart_err_msg.setGeometry(QtCore.QRect(430, 20, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_err_msg.setFont(font)
        self.tbl_chart_err_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_err_msg.setObjectName("tbl_chart_err_msg")
        self.tbl_chart_cross = QtWidgets.QLabel(self.frame)
        self.tbl_chart_cross.setGeometry(QtCore.QRect(140, 0, 931, 471))
        self.tbl_chart_cross.setScaledContents(True)
        self.tbl_chart_cross.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_cross.setObjectName("tbl_chart_cross")
        self.tbl_chart_err_description = QtWidgets.QLabel(self.frame)
        self.tbl_chart_err_description.setGeometry(QtCore.QRect(160, 330, 891, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbl_chart_err_description.setFont(font)
        self.tbl_chart_err_description.setAlignment(QtCore.Qt.AlignCenter)
        self.tbl_chart_err_description.setObjectName("tbl_chart_err_description")
        self.label.raise_()
        self.tbl_chart_cross.raise_()
        self.tbl_chart_X1.raise_()
        self.tbl_chart_Dz.raise_()
        self.tbl_chart_c.raise_()
        self.tbl_chart_Dopr.raise_()
        self.tbl_chart_Dg.raise_()
        self.tbl_chart_Lopr.raise_()
        self.tbl_chart_b.raise_()
        self.tbl_chart_a.raise_()
        self.tbl_chart_Sg.raise_()
        self.tbl_chart_err_msg.raise_()
        self.tbl_chart_err_description.raise_()
        self.gridLayout.addWidget(self.frame, 9, 0, 1, 9)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.tbl_main_widget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tbl_line, self.tbl_btn_save)
        Dialog.setTabOrder(self.tbl_btn_save, self.tbl_btn_print)
        Dialog.setTabOrder(self.tbl_btn_print, self.scrollArea)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Результат расчета"))
        self.tbl_b.setText(_translate("Dialog", "11111"))
        self.tbl_En.setText(_translate("Dialog", "11111"))
        self.label_Dvp_42.setText(_translate("Dialog", "Коэффициент овализации \"ksi\""))
        self.tbl_Lz.setText(_translate("Dialog", "11111"))
        self.tbl_Lopr.setText(_translate("Dialog", "11111"))
        self.tbl_date.setText(_translate("Dialog", "12.12.12 16:33:25"))
        self.label_Dvp_5.setText(_translate("Dialog", "Обжатие перед носком оправки Eн, %"))
        self.label_Dvp_38.setText(_translate("Dialog", "Коэффициент вытяжки \"mu\""))
        self.label_Dvp_34.setText(_translate("Dialog", "Угол подачи \"beta\", град"))
        self.tbl_btn_print.setText(_translate("Dialog", "Печать"))
        self.tbl_Dopr.setText(_translate("Dialog", "11111"))
        self.tbl_Dvh.setText(_translate("Dialog", "11111"))
        self.tbl_Sg.setText(_translate("Dialog", "11111"))
        self.tbl_GF.setText(_translate("Dialog", "11111"))
        self.label_Dvp_6.setText(_translate("Dialog", "Обжатие в пережиме Eп, %"))
        self.label_Dvp_36.setText(_translate("Dialog", "Расстояние между валками (выход) Dвых, мм"))
        self.tbl_ksi.setText(_translate("Dialog", "11111"))
        self.label_Dvp_2.setText(_translate("Dialog", "Диаметр заготовки Dз, мм"))
        self.label_Dvp_12.setText(_translate("Dialog", "Расч. полож. нажимных винтов"))
        self.label_Dvp_10.setText(_translate("Dialog", "Длина оправки Lопр, мм"))
        self.tbl_button.setText(_translate("Dialog", "K288"))
        self.label_Dvp_13.setText(_translate("Dialog", "Длина заготовки Lз, мм/3"))
        self.tbl_Lg.setText(_translate("Dialog", "11111"))
        self.label_Dvp_31.setText(_translate("Dialog", "Внутренний диаметр гильзы dг, мм"))
        self.tbl_Dvp.setText(_translate("Dialog", "11111"))
        self.tbl_btn_save.setText(_translate("Dialog", "Сохранить"))
        self.label_Dvp_9.setText(_translate("Dialog", "Расстояние между линейками на выходе L, мм"))
        self.label_Dvp_7.setText(_translate("Dialog", "Расстояние между валками в пережиме a, мм"))
        self.tbl_a.setText(_translate("Dialog", "11111"))
        self.tbl_L.setText(_translate("Dialog", "11111"))
        self.label_Dvp_3.setText(_translate("Dialog", "Диаметр оправки Dопр, мм"))
        self.label_Dvp_37.setText(_translate("Dialog", "Толщина стенки гильзы Sг, мм"))
        self.label_Dvp_43.setText(_translate("Dialog", "Угол раскатки \"fi\", град"))
        self.tbl_Dvih.setText(_translate("Dialog", "11111"))
        self.tbl_Een.setText(_translate("Dialog", "11111"))
        self.label_Dvp.setText(_translate("Dialog", "Диаметр валка в пережиме Dвп, мм"))
        self.tbl_dg.setText(_translate("Dialog", "11111"))
        self.label_Dvp_45.setText(_translate("Dialog", "Коэффициент вторичного захвата GF"))
        self.label_Dvp_41.setText(_translate("Dialog", "Расстояние между валками (вход) Dвх, мм"))
        self.tbl_beta.setText(_translate("Dialog", "11111"))
        self.label_Dvp_8.setText(_translate("Dialog", "Расстояние между линейками (переж.) b, мм"))
        self.label_Dvp_4.setText(_translate("Dialog", "Наружный диаметр гильзы Dг, мм"))
        self.label_Dvp_11.setText(_translate("Dialog", "Выдвижение носка оправки за пережим с, мм"))
        self.tbl_mu.setText(_translate("Dialog", "11111"))
        self.tbl_Dz.setText(_translate("Dialog", "11111"))
        self.tbl_screws.setText(_translate("Dialog", "11111"))
        self.tbl_fi.setText(_translate("Dialog", "11111"))
        self.label_Dvp_14.setText(_translate("Dialog", "Длина гильзы Lг, мм"))
        self.tbl_c.setText(_translate("Dialog", "11111"))
        self.tbl_Dg.setText(_translate("Dialog", "11111"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/images/NEW_table_chart.jpg\" height=\"470\"/></p></body></html>"))
        self.tbl_chart_X1.setText(_translate("Dialog", "300"))
        self.tbl_chart_Dz.setText(_translate("Dialog", "300"))
        self.tbl_chart_c.setText(_translate("Dialog", "300"))
        self.tbl_chart_Dopr.setText(_translate("Dialog", "300"))
        self.tbl_chart_Dg.setText(_translate("Dialog", "300"))
        self.tbl_chart_Lopr.setText(_translate("Dialog", "300"))
        self.tbl_chart_b.setText(_translate("Dialog", "300"))
        self.tbl_chart_a.setText(_translate("Dialog", "300"))
        self.tbl_chart_Sg.setText(_translate("Dialog", "300"))
        self.tbl_chart_err_msg.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#aa0000;\">Некорректный расчет!!!</span></p></body></html>"))
        self.tbl_chart_err_description.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#aa0000;\">Некорректный расчет!!!</span></p></body></html>"))
import source_rc
